apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "teste-ingress-stack-26"
  annotations:
    github.com/project-slug: sandrojrcorp/teste-ingress-stack-26
    backstage.io/techdocs-ref: dir:.
    vault.io/secrets-path: devportal
spec:
  type: devops
  lifecycle: experimental
  owner: "group:default/admin"
